// North-east, part 2: Myanmar, Bangladesh, Bhutan and China frontiers of the
// Border timelines and the references they cite. Edited by hand: no build step —
// save the file and reload india-borders.html. Format: timelines/README.md.

TIMELINES.ne2 = {
  "refs": {
    // Myanmar borders: Arunachal Pradesh, Nagaland, Manipur, Mizoram
    "nx_yandabo": ["Treaty of Yandabo", "Wikipedia: 24 February 1826; Burma cedes Assam and Manipur and agrees to stop interfering on the frontier.", "https://en.wikipedia.org/wiki/Treaty_of_Yandabo"],
    "nx_kabaw": ["Kabaw Valley", "Wikipedia: transfer to Burmese administration on 9 January 1834 and the Pemberton line drawn to its west; compensation payments to Manipur discontinued in 1953.", "https://en.wikipedia.org/wiki/Kabaw_Valley"],
    "nx_kabawcomp": ["Agreement Regarding Compensation for the Kubo (Kabaw) Valley (1834)", "Wikipedia: signed 25 January 1834 at Langthabal between Major F. J. Grant/Captain R. B. Pemberton and Raja Gambhir Singh of Manipur; monthly allowance of 500 Sicca rupees.", "https://en.wikipedia.org/wiki/Agreement_Regarding_Compensation_for_the_Kubo_(Kabaw)_Valley_(1834)"],
    "nx_pemberton": ["Robert Boileau Pemberton", "Wikipedia: the 1834 Manipur–Kabaw Valley line and the 1894 Manipur–Chin Hills boundary drawn close to it.", "https://en.wikipedia.org/wiki/Robert_Boileau_Pemberton"],
    "nx_johnstone": ["“Contested history”", "ForumIAS Blog: the 1834 Pemberton line, its 1881 revision by Colonel James Johnstone (Chassad tract), the 1896 Pemberton–Johnstone–Maxwell line and its 1967 ratification.", "https://forumias.com/blog/contested-history/"],
    "nx_burma1937": ["Burma separated from British India, 1 April 1937", "The Irrawaddy: the Government of Burma Act 1935 took effect on 1 April 1937, making Burma a separate Crown colony under Premier Ba Maw.", "https://www.irrawaddy.com/specials/on-this-day/burma-separated-british-india-82-years-ago-today.html"],
    "nx_1967brookings": ["India and Myanmar: the boundary agreement of 1967", "Brookings (Sambandh blog): the Rangoon agreement of 10 March 1967 formalised a colonial-era administrative line; Mizo and Naga insurgencies pushed India to settle it; mapping errors cost India ground near Moreh.", "https://www.brookings.edu/articles/sambandh-blog-india-and-myanmar-the-role-of-domestic-calculations-in-the-boundary-agreement-of-1967/"],
    "nx_lushaihills": ["British rule in the Lushai Hills", "Wikipedia: the January 1892 Chin-Lushai Conference, the Viceroy’s ruling of 2 August 1892 keeping the Chin Hills under Burma, the 1898 unification of the Lushai Hills district and the 1901 boundary commission.", "https://en.wikipedia.org/wiki/British_rule_in_the_Lushai_Hills"],
    "nx_arunstate": ["Arunachal Pradesh Day", "Wikipedia: statehood on 20 February 1987 as India’s 24th state.", "https://en.wikipedia.org/wiki/Arunachal_Pradesh_Day"],
    "nx_nefa": ["Arunachal Pradesh: the evolution from NEFA to statehood", "BA Notes: NEFA constituted 1954; renamed the Union Territory of Arunachal Pradesh in 1972; full statehood in 1987.", "https://banotes.org/democracy-development-northeast/arunachal-pradesh-evolution-nefa-statehood/"],
    "nx_mizostate": ["Mizoram (union territory)", "Wikipedia: created a Union Territory on 21 January 1972 under the North-Eastern Areas (Reorganisation) Act, 1971; statehood 20 February 1987.", "https://en.wikipedia.org/wiki/Mizoram_(union_territory)"],
    "nx_nagahills": ["Naga Hills District, British India", "Wikipedia: district created 1866, with the Lotha (1875), Ao (1889), Sümi (1904) and Konyak (1910) tracts annexed to it.", "https://en.wikipedia.org/wiki/Naga_Hills_District,_British_India"],
    // Bangladesh borders: Assam, Meghalaya, Tripura, Mizoram
    "nx_asurarali": ["Treaty of Asurar Ali, February 1639", "Wikipedia: Allah Yar Khan for the Mughals and Momai Tamuli for the Ahoms fix the frontier at the Barnadi on the north bank and the Asurar Ali causeway at Guwahati on the south.", "https://en.wikipedia.org/wiki/Treaty_of_Asurar_Ali"],
    "nx_itakhuli": ["Battle of Itakhuli, 1682", "Wikipedia: the Ahoms drive the Mughals about 100 km west, after which the Manas is the Ahom–Mughal boundary until the British arrive.", "https://en.wikipedia.org/wiki/Battle_of_Itakhuli"],
    "nx_goalpara": ["Undivided Goalpara district", "Wikipedia: Mughal sarkar Dhekuri, lying between the Sankosh and the Manas, passed to the Company with Bengal and was administered from Rangpur until Regulation X of 1822 severed it as “North-East Rangpur”.", "https://en.wikipedia.org/wiki/Undivided_Goalpara_district"],
    "nx_sylhet": ["Undivided Sylhet district", "Wikipedia: transfer from Bengal to Assam in September 1874, the 6–7 July 1947 referendum (423,660 for East Bengal to 123,155 for Assam) and the retention of Karimganj sub-division by India.", "https://en.wikipedia.org/wiki/Undivided_Sylhet_district"],
    "nx_radcliffe": ["Radcliffe Line", "Wikipedia: the Bengal Boundary Commission’s award of 17 August 1947, its Muslim/non-Muslim contiguous-majority principle, and the award of the 97%-non-Muslim Chittagong Hill Tracts to Pakistan; Karimganj later became an Assam district in 1983.", "https://en.wikipedia.org/wiki/Radcliffe_Line"],
    "nx_cht": ["Brief History of the Chittagong Hill Tracts", "UPDFCHT: British annexation in 1860, the Chittagong Hill Tracts Regulation of 1900, and the 1947 award of the CHT to Pakistan despite its non-Muslim majority.", "https://updfcht.com/?page_id=45"],
    "nx_lba": ["India–Bangladesh enclaves", "Wikipedia: the Indira–Mujib Land Boundary Agreement signed 16 May 1974, the September 2011 Additional Protocol, the Constitution (100th Amendment) Act’s passage in May 2015, and the enclave exchange at midnight on 31 July/1 August 2015 (India gained 51 enclaves, 7,110 acres; Bangladesh gained 111, 17,160 acres).", "https://en.wikipedia.org/wiki/India%E2%80%93Bangladesh_enclaves"],
    "nx_tripurastate": ["Tripura (princely state)", "Wikipedia: the Chakla Roshnabad zamindari in the Comilla/Noakhali/Sylhet plains, British protectorate status from 1809, recognition of the Rajas as sovereigns in 1838, and inclusion in Eastern Bengal and Assam as ‘Hill Tippera’ from 1905.", "https://en.wikipedia.org/wiki/Tripura_(princely_state)"],
    "nx_hunter_tipperah": ["A Statistical Account of Bengal, vol. VI (1876): Tipperah District", "W. W. Hunter (comp. H. M. Kisch), pp. 358–359 and 427: the kingdom independent until Shujá-ud-dín Khán ‘reduced it to subjection about the year 1733’ (other authorities give 1728 or 1739); only the lowlands placed on the rent-roll of Bengal, the hills left to the Rájá; the Jalálpur division and its administration after 1765.", "https://archive.org/details/dli.bengal.10689.7304"],
    "nx_hunter_hilltipperah": ["A Statistical Account of Bengal, vol. VI (1876): Hill Tipperah", "W. W. Hunter, pp. 460 and 465–470, after Captain W. L. Samuells’ 1875 report: the western boundary with Tipperah District defined in 1854 by the arbitrators Mr Leycester and Mr Campbell; Nawab Fathi Jang’s invasion about 1620; Todar Mall’s rent-roll of 1582; the 1728 invasion that put the plains on the rent-roll as Roshnábád; the hills tributary to the Nawab; the Company’s share from 1765; Durgá Mánik recognised in 1808; the Rájá ‘on the plains … a British subject and a zamíndár’.", "https://archive.org/details/dli.bengal.10689.7304"],
    "nx_ig_hilltippera": ["Imperial Gazetteer of India, vol. XIII (1908): Hill Tippera", "pp. 117–119: invasions of 1279, the mid-14th century and 1620; the plains ‘not annexed to the Mughal empire until 1733’ while ‘Hill Tippera proper was never assessed to revenue’; investiture since 1808; the 1838 ruling on the Rájá’s prescriptive right to the hills, from unchallenged possession since at least 1793; Chakla Roshnabad, 570 sq. miles in Tippera, Noakhali and Sylhet.", "https://archive.org/details/imperialgazettee13grea"],
    "nx_ig_tippera": ["Imperial Gazetteer of India, vol. XXIII (1908): Tippera District", "pp. 381–382: the District part of the Rájá’s dominions until 1733, when Shuja-ud-dín Khán overran the plains and they ‘became an integral part of the Mughal empire’; the Company from 1765, with more than a fifth of the District still under the Rájá’s immediate rule; the Jalalpur ihtimam; Tippera and Noakhali one revenue charge in 1781.", "https://archive.org/details/imperialgazettee23greauoft"],
    "nx_bp_tripura": ["Tripura", "Banglapedia (Sirajul Islam): the Rájá declared a zamindar for his plains territory, named Pargana Roushanabad, under Murshid Quli Khan; the zamindari the core of Tippera District from 1790; its loss under the East Bengal State Acquisition and Tenancy Act, 1950.", "https://en.banglapedia.org/index.php/Tripura"],
    "nx_bp_shamsher": ["Shamsher Gazi", "Banglapedia (Ali Nawaz): his rise in Chakla Raushanabad in the 1740s, his capture of Udaipur, Krishna Manikya’s appeal to Nawab Mir Qasim, and his death in 1760.", "https://en.banglapedia.org/index.php/Shamsher_Gazi"],
    "nx_kalyanmanikya": ["Kalyan Manikya", "Wikipedia: the Mughal capture of Tripura in 1618 and withdrawal after an epidemic; Kalyan’s defeat by Shah Shuja in 1658 and Tripura’s entry on the Mughal revenue roll as ‘Sarkar Udaipur’.", "https://en.wikipedia.org/wiki/Kalyan_Manikya"],
    "nx_govindamanikya": ["Govinda Manikya", "Wikipedia: Maharaja of Tripura 1660–61 and 1667–76; five elephants a year sent as tribute to the Mughal emperor, with Tripura enjoying de facto independent status.", "https://en.wikipedia.org/wiki/Govinda_Manikya"],
    "nx_comilladiv": ["Comilla Division", "Wikipedia: Tippera District established by the British in 1790 and renamed Comilla in 1960; its Brahmanbaria and Chandpur subdivisions made separate districts in 1984.", "https://en.wikipedia.org/wiki/Comilla_Division"],
    "nx_tripuramerger": ["Tripura Merger Agreement", "Wikipedia: signed 9 September 1949 by Regent Maharani Kanchan Prava Devi, effective 15 October 1949.", "https://en.wikipedia.org/wiki/Tripura_Merger_Agreement"],
    "nx_khasijaintia": ["Khasi and Jaintia Hills", "Wikipedia: organised as a district of Assam from 1912 to 1947, immediately north of the Sylhet plains.", "https://en.wikipedia.org/wiki/Khasi_and_Jaintia_Hills"],
    "nx_jaintia": ["Jaintia Kingdom", "Wikipedia: the Mughal campaign that brought the Jaintia raja back under imperial control after his revolt of the 1670s, and the British annexation of the kingdom on 15 March 1835.", "https://en.wikipedia.org/wiki/Jaintia_Kingdom"],
    "nx_meghstate": ["Meghalaya’s journey from “state within a state” to full statehood", "PolSci Institute: the autonomous state of Meghalaya formed 2 April 1970 under the Assam Reorganisation (Meghalaya) Act, 1969, and full statehood on 21 January 1972 under the North-Eastern Areas (Reorganisation) Act, 1971.", "https://polsci.institute/india-political-process/meghalaya-journey-to-full-statehood/"],
    // Bhutan borders: Arunachal Pradesh, Assam
    "nx_assamduars": ["The Duar War, 1864–1865", "onwar.com: Britain’s 1841 annexation of the Assam Duars for an annual Rs 10,000 compensation, the failed 1863 Eden mission, the war declared 12 November 1864, and the Treaty of Sinchula’s cession of the Bengal and Assam Duars plus the Kalimpong tract for a subsidy rising to Rs 50,000.", "https://onwar.com/data/britbhutan1865.html"],
    "nx_punakha": ["Treaty of Punakha", "Wikipedia: signed 8 January 1910, effective 10 January; it amended the 1865 Treaty of Sinchula’s financial and diplomatic articles, doubling the subsidy and giving Britain charge of Bhutan’s external relations, without altering the boundary.", "https://en.wikipedia.org/wiki/Treaty_of_Punakha"],
    "nx_1949treaty": ["Treaty of Perpetual Peace and Friendship between India and Bhutan (1949)", "Advocatetanmoy: signed 8 August 1949 at Darjeeling; India to return about 32 square miles of the Dewangiri tract within a year and pay an annual subsidy of five lakh rupees.", "https://advocatetanmoy.com/peace-treaty-india-bhutan/"],
    "nx_bhutanindiaborder": ["Bhutan–India border", "Wikipedia: the 1774 peace treaty, the 1841–42 Duars annexation, the 1865/1910/1949 treaties, boundary delimitation surveys of 1973–1984 with minor disagreements on the Arunachal Pradesh stretch, and a final demarcation treaty in 2006.", "https://en.wikipedia.org/wiki/Bhutan%E2%80%93India_border"],
    // China border: Arunachal Pradesh
    "nx_simla1914": ["Simla Accord (1914)", "Wikipedia: negotiated at Simla between Britain’s Henry McMahon and Tibet’s Lonchen Shatra; China’s delegate Ivan Chen initialled the draft on 27 April 1914 but never signed the final convention of 3 July 1914.", "https://en.wikipedia.org/wiki/Simla_Accord_(1914)"],
    "nx_tawang1951": ["Ralengnao Khathing", "Wikipedia: Assam Rifles troops under Major Ralengnao “Bob” Khathing took possession of Tawang and raised Indian administration up to the McMahon Line (dated 1951 in most accounts, 1950 in this article).", "https://en.wikipedia.org/wiki/Ralengnao_Khathing"],
    "nx_mcmahon": ["McMahon Line", "Wikipedia: the 1914 Simla Convention line, its non-enforcement until the 1950s, the 1962 war (Chinese forces advancing to Walong and near Bomdila before withdrawing to the line), and the present dispute, with China rejecting the line while treating it as part of the Line of Actual Control.", "https://en.wikipedia.org/wiki/McMahon_Line"],
    "nx_cbm1996": ["Agreement on Military Confidence Building Measures, 1996", "Wikipedia: signed in New Delhi on 29 November 1996, limiting forces and weapons near the Line of Actual Control and setting up flag-meeting procedures, while noting differing perceptions of the LAC’s alignment in places.", "https://en.wikipedia.org/wiki/Agreement_on_Military_Confidence_Building_Measures,_1996"]
  },
  "timelines": {
    "Arunachal Pradesh|Myanmar": [
      ["1826", "The Treaty of Yandabo ends the First Anglo-Burmese War: Burma cedes Assam and agrees to stop interfering on the frontier, bringing the tracts north of the Patkai within the British sphere even though no precise line is drawn there.", ["nx_yandabo"]],
      ["1826–1937", "Burma itself remains a province of British India, so the Patkai range functions only as an internal administrative watershed between Assam’s frontier tracts and Burma, not an international boundary.", ["nx_burma1937"]],
      ["1 Apr 1937", "The Government of Burma Act 1935 separates Burma from British India; the Patkai watershed, already the practical edge of British administration on this stretch, becomes an international frontier.", ["nx_burma1937"]],
      ["1954", "The North-East Frontier Agency (NEFA) is constituted to administer the tracts on the Indian side of the Patkai, including what are now Arunachal’s Changlang and Anjaw districts.", ["nx_nefa"]],
      ["10 Mar 1967", "India and Burma sign a boundary agreement at Rangoon delimiting and demarcating their entire common frontier, from the China trijunction to the Bangladesh trijunction, largely following the traditional Patkai watershed in this sector.", ["nx_1967brookings"]],
      ["21 Jan 1972", "NEFA is renamed and made the Union Territory of Arunachal Pradesh; the demarcated Patkai line becomes its external frontier with Burma.", ["nx_nefa", "nx_arunstate"]],
      ["20 Feb 1987", "Arunachal Pradesh becomes India’s 24th state under the State of Arunachal Pradesh Act, 1986; the Patkai line remains its boundary with Myanmar.", ["nx_arunstate"]]
    ],
    "Myanmar|Nagaland": [
      ["1826", "The Treaty of Yandabo ends the First Anglo-Burmese War and brings the Naga-inhabited hills within the British sphere, though the frontier beyond the Patkai watershed is left undefined.", ["nx_yandabo"]],
      ["1866–1910", "British Assam creates the Naga Hills district in 1866 and extends it east through the annexation of Lotha (1875), Ao (1889), Sümi (1904) and Konyak (1910) tracts, its unadministered far side approaching the Patkai.", ["nx_nagahills"]],
      ["1 Apr 1937", "Burma is separated from British India under the Government of Burma Act 1935; the Patkai watershed, the practical limit of British administration here, becomes an international frontier.", ["nx_burma1937"]],
      ["10 Mar 1967", "India and Burma sign the Rangoon boundary agreement, delimiting and demarcating the whole common frontier, including the Patkai stretch bordering Naga country.", ["nx_1967brookings"]],
      ["1 Dec 1963", "Nagaland becomes India’s 16th state under the State of Nagaland Act, 1962; the demarcated Patkai line becomes its boundary with Myanmar.", ["m5"]]
    ],
    "Manipur|Myanmar": [
      ["1826", "The Treaty of Yandabo ends the First Anglo-Burmese War: Burma renounces its claims to Manipur, whose eastern limit towards the Kabaw Valley is left undefined.", ["nx_yandabo"]],
      ["9 Jan 1834", "Manipur, which had held the Kabaw Valley since the war, is required to hand it back to Burmese administration.", ["nx_kabaw"]],
      ["25 Jan 1834", "At Langthabal, Grant and Pemberton draw the Pemberton line along the base of the Yomadong (Muring) hills west of the Kabaw Valley; Manipur is compensated with a monthly allowance of 500 Sicca rupees, to lapse if the valley is ever restored to it.", ["nx_pemberton", "nx_kabawcomp"]],
      ["1881", "A commission under Colonel James Johnstone shifts the line to keep the disputed Chassad tract inside Manipur, producing the Pemberton–Johnstone line; Burma is invited but does not attend.", ["nx_johnstone"]],
      ["1896", "A further revision, adding surveyor Maxwell’s name, produces the Pemberton–Johnstone–Maxwell line, which becomes the standard reference boundary.", ["nx_johnstone"]],
      ["21 Sep 1949", "The Manipur Merger Agreement brings the princely state into the Indian Union with its existing external limits intact.", ["m34"]],
      ["3 Mar 1953", "Nehru and Burmese premier U Nu agree to end the compensation payments for the Kabaw Valley, discontinuing a subsidy that had run for more than a century.", ["nx_kabaw"]],
      ["10 Mar 1967", "India and Burma sign the Rangoon boundary agreement ratifying the Pemberton–Johnstone–Maxwell line; errors in the accompanying maps left some Manipuri-claimed ground, including territory near Moreh, on the Myanmar side.", ["nx_johnstone", "nx_1967brookings"]]
    ],
    "Mizoram|Myanmar": [
      ["1826", "The Treaty of Yandabo brings Cachar within the British sphere; the Lushai Hills to its south remain unadministered and only loosely bounded from the Chin Hills to their east.", ["nx_yandabo"]],
      ["25–29 Jan 1892", "At a Chin-Lushai Conference in Calcutta, officials debate uniting the Chin and Lushai Hills under one administration; the Chief Commissioner of Burma objects.", ["nx_lushaihills"]],
      ["2 Aug 1892", "The Viceroy rules that the Chin Hills stay under Burma, separate from the Lushai Hills under Assam — the origin of today’s Mizoram–Myanmar line.", ["nx_lushaihills"]],
      ["1 Apr 1898", "The North and South Lushai Hills are merged into a single Lushai Hills district under Assam, with Aizawl as headquarters.", ["nx_lushaihills"]],
      ["1901", "A boundary commission demarcates the Chin–Lushai frontier along the Tuipui and Tuisai streams into the Tuimang and Bopuilui, up to the source of the Tyao river.", ["nx_lushaihills"]],
      ["1 Apr 1937", "Burma is separated from British India under the Government of Burma Act 1935; the 1892/1901 Chin–Lushai administrative line becomes an international frontier.", ["nx_burma1937", "nx_lushaihills"]],
      ["10 Mar 1967", "India and Burma sign the Rangoon boundary agreement, delimiting and demarcating the whole common frontier, including this stretch.", ["nx_1967brookings"]],
      ["21 Jan 1972", "The Lushai Hills, by then renamed Mizo Hills, become the Union Territory of Mizoram under the North-Eastern Areas (Reorganisation) Act, 1971; the demarcated Chin Hills line becomes its boundary with Myanmar.", ["m7", "nx_mizostate"]],
      ["20 Feb 1987", "Mizoram becomes India’s 23rd state under the State of Mizoram Act, 1986.", ["nx_mizostate"]]
    ],
    "Assam|Bangladesh": [
      ["1639–1682", "Mughal Bengal’s frontier against the Ahom kingdom is fixed by the Treaty of Asurar Ali in February 1639 at the Barnadi on the Brahmaputra’s north bank and the Asurar Ali causeway at Guwahati on the south, then pushed back to the Manas after the Ahom victory at Itakhuli in 1682. Both lines lie deep inside modern Assam, so no part of this border descends from them.", ["nx_asurarali", "nx_itakhuli"]],
      ["1822", "West of the Manas, Mughal sarkar Dhekuri — the later Goalpara — lay inside Bengal Subah alongside Rangpur, so there is no old provincial line in this sector at all: it is cut by Regulation X of 1822, which severs Goalpara, Dhubri and Koraibari from Rangpur as “North-East Rangpur”, constituted a district in 1833 and attached to Assam.", ["nx_goalpara"]],
      ["Sep 1874", "Sylhet district, previously part of Bengal and valued for its tea revenue, is transferred to the new Assam Chief-Commissionership, setting Assam’s southern frontier against the Bengal districts to its south.", ["nx_sylhet"]],
      ["6–7 Jul 1947", "A referendum asks Sylhet’s voters whether the district should join the future East Bengal; 423,660 vote to join against 123,155 to remain with Assam.", ["nx_sylhet"]],
      ["17 Aug 1947", "The Radcliffe Bengal Boundary Commission’s award sends most of Sylhet to East Bengal but, after local lobbying, keeps the Karimganj sub-division — three and a half thanas — with India as part of Assam, giving the Barak Valley its present shape.", ["m13", "nx_sylhet"]],
      ["1983", "Karimganj becomes a separate Assam district; its western edge along the former Sylhet line is the international border.", ["nx_radcliffe"]],
      ["16 May 1974", "The Indira–Mujib Land Boundary Agreement addresses enclaves and adverse possessions along the whole India–Bangladesh border, including Assam’s stretch.", ["nx_lba"]],
      ["31 Jul–1 Aug 2015", "The Constitution (100th Amendment) Act, 2015 gives the 1974 agreement and its 2011 protocol legal effect; outstanding adverse possessions are settled and the boundary, including Assam’s section, is finally demarcated.", ["m28", "nx_lba"]]
    ],
    "Bangladesh|Meghalaya": [
      ["Mughal era", "Mughal Bengal reaches only the foot of the hills. The Jaintia raja’s plains territory is brought back under imperial control after his revolt of the 1670s, but the Khasi, Jaintia and Garo hills above are never administered as Mughal territory — a plains–hills divide the British inherit, annexing the Jaintia kingdom separately on 15 March 1835.", ["nx_jaintia"]],
      ["1874", "Sylhet is transferred from Bengal to the new Assam province; the Khasi and Jaintia Hills, already under British administration, sit immediately north of the Sylhet and Mymensingh plains.", ["nx_sylhet", "nx_khasijaintia"]],
      ["1912", "The Khasi and Jaintia Hills and the Garo Hills are organised as districts of Assam; their southern limits against Sylhet and Mymensingh become the line later inherited by Meghalaya.", ["nx_khasijaintia"]],
      ["17 Aug 1947", "The Radcliffe Bengal Boundary Commission’s award places Sylhet and Mymensingh in East Bengal, fixing the hills–plains district line as an international border.", ["m13"]],
      ["2 Apr 1970", "Meghalaya is created as an autonomous state within Assam, combining the Khasi &amp; Jaintia Hills and Garo Hills districts and their Bangladesh-facing frontier.", ["nx_meghstate"]],
      ["21 Jan 1972", "Meghalaya becomes a full state under the North-Eastern Areas (Reorganisation) Act, 1971.", ["m7", "nx_meghstate"]],
      ["2015", "The Constitution (100th Amendment) Act, 2015 gives effect to the 1974 Land Boundary Agreement and its 2011 protocol, settling adverse possessions and completing demarcation along Meghalaya’s border.", ["m28", "nx_lba"]]
    ],
    "Bangladesh|Tripura": [
      ["1279 – c. 1620", "The Tripura kingdom holds both its hills and the plains to the west that later became Tippera (Comilla) District. Bengal’s rulers invade in 1279, around 1345 and, under the Mughal commander Nawab Fateh Jang, around 1620 (1618 in some accounts), when Udaipur, the capital, is held for about two and a half years before an epidemic drives the Mughals out. Each time the Rajas keep their independence. There is <strong>no fixed line yet</strong>: Hunter notes that the kingdom’s limits cannot be defined at any given period, as its reach into the Bengal plains rose and fell.", ["nx_ig_hilltippera", "nx_ig_tippera", "nx_hunter_hilltipperah", "nx_kalyanmanikya"]],
      ["1582 – 1658", "The western and southern plains appear on Mughal revenue rolls, first on Todar Mall’s rent-roll of 1582. The historian Grant held that they were not actually conquered until Shah Jahan’s reign. In 1658 Prince Shah Shuja defeats Kalyan Manikya, and Tripura is entered on the revenue roll as ‘Sarkar Udaipur’, but under Govinda Manikya the kingdom again enjoys de facto independence, sending the emperor a tribute of elephants.", ["nx_hunter_hilltipperah", "nx_kalyanmanikya", "nx_govindamanikya"]],
      ["c. 1728 – 1733", "<strong>The origin of the line.</strong> Nawab Shuja-ud-Din Khan’s forces overrun the plains, which become an integral part of the Mughal province of Bengal. They are entered on its rent-roll as <em>Chakla Roshnabad</em> in the Jalalpur division, and the Raja keeps them as a revenue-paying estate (zamindari). The hills are never assessed to revenue and remain the Raja’s, tributary to the Nawab and paying chiefly in elephants. This divide between Bengal’s taxed plains and the Raja’s untaxed hills is what the Tripura–Bangladesh border still follows. <em>Sources differ on the date:</em> Hunter gives about 1733 and notes others give 1728 or 1739, while his Hill Tipperah chapter says 1728. The Imperial Gazetteer says 1733. Banglapedia puts the Raja’s recognition as zamindar of ‘Pargana Roushanabad’ earlier still, under Murshid Quli Khan.", ["nx_hunter_tipperah", "nx_hunter_hilltipperah", "nx_ig_tippera", "nx_ig_hilltippera", "nx_bp_tripura"]],
      ["1748 – 1760", "Shamsher Gazi, who rose within Chakla Roshnabad, takes over the plains estate and then Udaipur itself. Raja Krishna Manikya flees and appeals to Nawab Mir Qasim, and Shamsher is killed in 1760, restoring the Manikyas. The sources disagree on who he was: Banglapedia calls him a peasant-born ruler, while Hunter calls him a Muslim governor whom the Nawab had executed.", ["nx_bp_shamsher", "nx_hunter_hilltipperah"]],
      ["1765", "The East India Company takes the <em>diwani</em> of Bengal. Only ‘so much of Tipperah as had been placed on the rent-roll of Bengal’ passes to it, so the Nawabi revenue line becomes the frontier between British Bengal and the Raja’s hill state. Krishna Manikya holds the throne with English backing. The plains are administered as part of Jalalpur, joined with Noakhali as one revenue charge in 1781. Tippera District forms around the Raja’s Roshnabad zamindari from 1790, and he holds that estate as an ordinary British zamindar.", ["nx_hunter_hilltipperah", "nx_hunter_tipperah", "nx_ig_tippera", "nx_bp_tripura"]],
      ["1808 – 1809", "The British Government recognises Durga Manikya as Raja. From then on every Raja is invested by the British, which is the start of Tripura’s status as a British protectorate. The hill state stays internally independent, while its plains estate, Chakla Roshnabad (in the Tippera, Noakhali and Sylhet plains), is British territory. Hunter and the Imperial Gazetteer date the recognition 1808, and Wikipedia gives 1809.", ["nx_hunter_hilltipperah", "nx_ig_hilltippera", "nx_tripurastate"]],
      ["1838", "The Deputy-Governor of Bengal rules that the Raja has a prescriptive right to the territory within the hills, because he has held it unchallenged since at least 1793, the year of the Permanent Settlement. In effect the British recognise the Manikya Rajas as sovereigns of the hill state.", ["nx_ig_hilltippera", "nx_tripurastate"]],
      ["1854", "<strong>The line is fixed on the ground.</strong> Hill Tipperah’s western boundary with the British district of Tipperah is defined by the award of two arbitrators: Mr Leycester for the British Government and Mr Campbell for the Raja. It is the origin of the stretch facing the old Tippera District, renamed Comilla in 1960 and since split into Comilla, Brahmanbaria and Chandpur districts.", ["nx_hunter_hilltipperah", "nx_comilladiv"]],
      ["1905", "Tripura is placed alongside the short-lived province of Eastern Bengal and Assam, styled ‘Hill Tippera’; its boundary with the Bengal districts is unchanged.", ["nx_tripurastate"]],
      ["17 Aug 1947", "The Radcliffe Bengal Boundary Commission’s award places Comilla, Noakhali, Sylhet and the Chittagong Hill Tracts in East Bengal (later East Pakistan), while princely Tripura, hemmed in on three sides, stays outside Pakistan. The Raja’s plains estate, Chakla Roshnabad, lies on the Bengal side of the old line and goes to East Bengal with those districts. He loses it when East Bengal abolishes zamindaris in 1950.", ["m13", "nx_cht", "nx_bp_tripura"]],
      ["9 Sep 1949", "The Tripura Merger Agreement, signed by Regent Maharani Kanchan Prava Devi, brings the state into the Indian Union with effect from 15 October 1949, its existing external limits against East Pakistan intact.", ["nx_tripuramerger"]],
      ["21 Jan 1972", "Tripura becomes a full state under the North-Eastern Areas (Reorganisation) Act, 1971.", ["m7"]],
      ["2015", "The Constitution (100th Amendment) Act, 2015 gives effect to the 1974 Land Boundary Agreement and its 2011 protocol, settling adverse possessions along Tripura’s border with Bangladesh.", ["m28", "nx_lba"]]
    ],
    "Bangladesh|Mizoram": [
      ["1860", "The British occupy the Chittagong Hill Tracts, administered as an extension of Chittagong district; the Lushai country to its north and east remains outside British control.", ["nx_cht"]],
      ["2 Aug 1892", "The Viceroy’s decision keeping the Chin Hills under Burma, separate from the Lushai Hills, leaves the Lushai Hills’ southern neighbour as the Chittagong Hill Tracts, already under a separate Bengal administration.", ["nx_lushaihills"]],
      ["1900", "The Chittagong Hill Tracts Regulation gives the CHT a distinct, restricted-settlement administration under Bengal, sharpening its separation from the Lushai Hills district administered from Assam.", ["nx_cht"]],
      ["17 Aug 1947", "At independence the Chittagong Hill Tracts, despite a large non-Muslim majority, are awarded to Pakistan by the Radcliffe Bengal Boundary Commission; the inherited Lushai Hills–CHT administrative line becomes an international frontier.", ["m13", "nx_cht"]],
      ["21 Jan 1972", "The Lushai Hills, renamed Mizo Hills, become the Union Territory of Mizoram under the North-Eastern Areas (Reorganisation) Act, 1971.", ["m7", "nx_mizostate"]],
      ["2015", "The Constitution (100th Amendment) Act, 2015 gives effect to the 1974 Land Boundary Agreement and its 2011 protocol, settling adverse possessions and completing demarcation along Mizoram’s border with Bangladesh.", ["m28", "nx_lba"]],
      ["20 Feb 1987", "Mizoram becomes India’s 23rd state; the CHT line stays as its border with Bangladesh.", ["nx_mizostate"]]
    ],
    "Arunachal Pradesh|Bhutan": [
      ["1774", "A peace treaty between the East India Company, acting after intervening in a Cooch Behar succession dispute, and Bhutan gives the first British recognition of a Bhutanese frontier.", ["nx_bhutanindiaborder"]],
      ["1841", "Britain annexes the Assam Duars from Bhutan, paying an annual compensation of Rs 10,000; the British-administered plains now run up against the Bhutan hills along the future Arunachal sector.", ["nx_assamduars"]],
      ["1864–65", "The Duar War: Britain withholds the Duars compensation after a failed 1863 mission under Ashley Eden, then declares war on 12 November 1864; Bhutan loses about a fifth of its territory.", ["nx_assamduars"]],
      ["11 Nov 1865", "The Treaty of Sinchula: Bhutan cedes the Bengal and Assam Duars and the Kalimpong hill tract in perpetuity for an annual subsidy rising to Rs 50,000 — the cession line becomes the origin of the modern Bhutan–India frontier, including its eastern, Arunachal-facing stretch.", ["nx_assamduars"]],
      ["8 Jan 1910", "The Treaty of Punakha revises the 1865 settlement’s financial and diplomatic terms — doubling the subsidy and putting Bhutan’s foreign relations under British guidance — without moving the boundary.", ["nx_punakha"]],
      ["8 Aug 1949", "The India–Bhutan Treaty of Perpetual Peace and Friendship replaces the 1910 treaty; India agrees to return about 32 square miles of the Dewangiri tract to Bhutan within a year, adjusting the frontier’s eastern end.", ["nx_1949treaty"]],
      ["1973–1984", "Joint surveys delimit the boundary in detail; minor disagreements remain over short stretches next to Arunachal Pradesh.", ["nx_bhutanindiaborder"]],
      ["2006", "India and Bhutan sign a final border demarcation treaty settling the remaining stretches; the line stands as Arunachal Pradesh’s boundary with Bhutan.", ["nx_bhutanindiaborder"]]
    ],
    "Assam|Bhutan": [
      ["1774", "A peace treaty between the Company and Bhutan, following British intervention in a Cooch Behar succession dispute, gives the first British recognition of Bhutan’s southern frontier.", ["nx_bhutanindiaborder"]],
      ["1841", "Britain annexes the Assam Duars — lowland tracts in Darrang and Kamrup — from Bhutan, paying an annual compensation of Rs 10,000.", ["nx_assamduars"]],
      ["1864–65", "The Duar War: after Britain withholds the Duars compensation and a mission under Ashley Eden fails, war is declared on 12 November 1864; Bhutanese forces briefly retake ground before Britain prevails.", ["nx_assamduars"]],
      ["11 Nov 1865", "The Treaty of Sinchula: Bhutan permanently cedes the Bengal and Assam Duars, about a fifth of its territory, for an annual subsidy rising to Rs 50,000 — the origin of today’s Assam–Bhutan line.", ["nx_assamduars"]],
      ["8 Jan 1910", "The Treaty of Punakha revises the 1865 treaty’s terms, doubling the subsidy and giving Britain charge of Bhutan’s foreign relations, without moving the boundary.", ["nx_punakha"]],
      ["8 Aug 1949", "The India–Bhutan Treaty of Perpetual Peace and Friendship replaces the 1910 treaty and keeps the 1865 cession line as the international boundary along Assam.", ["nx_1949treaty"]],
      ["1973–1984", "Joint surveys formally delimit the boundary; the Assam stretch is settled without major dispute.", ["nx_bhutanindiaborder"]]
    ],
    "Arunachal Pradesh|China": [
      ["1913–14", "At the Simla Convention, British India’s Henry McMahon and Tibet’s Lonchen Shatra negotiate a boundary along the crest of the eastern Himalaya — the McMahon Line — while China’s delegate initials the draft in April 1914 but never signs the final convention of 3 July.", ["nx_simla1914"]],
      ["1914–1940s", "Britain does little to enforce the new line on the ground; Tawang continues to be administered through its monastery under Lhasa, and successive Chinese governments never recognise the convention.", ["nx_mcmahon"]],
      ["Feb 1951", "Assam Rifles troops under Major Ralengnao “Bob” Khathing take possession of Tawang and raise Indian administration up to the McMahon Line for the first time.", ["nx_tawang1951"]],
      ["1954", "The North-East Frontier Agency (NEFA) is constituted to administer the whole tract south of the McMahon Line, including Tawang.", ["nx_nefa"]],
      ["20 Oct–21 Nov 1962", "In the Sino-Indian War, Chinese forces cross the McMahon Line, take Tawang and advance about 30 km beyond Walong and close to Bomdila, before declaring a unilateral ceasefire and withdrawing back to the line.", ["nx_mcmahon"]],
      ["7 Sep 1993", "India and China sign the Border Peace and Tranquility Agreement, agreeing to respect the Line of Actual Control pending a boundary settlement.", ["bpta1993"]],
      ["29 Nov 1996", "A further agreement on military confidence-building measures limits forces and weapons near the LAC and sets up flag-meeting procedures, while recording “differing perceptions” of its exact alignment in places.", ["nx_cbm1996"]],
      ["1972–1987", "NEFA becomes the Union Territory and then, on 20 February 1987, the state of Arunachal Pradesh; China rejects the McMahon Line, calls the state “South Tibet” and claims most of it, while India administers up to the line, which functions as the de facto Line of Actual Control in this sector.", ["nx_arunstate", "nx_mcmahon"]]
    ]
  },
};
