# East: Bihar, Jharkhand, West Bengal, Odisha and the Bangladesh frontier.
# Executed inside timelines.py (ref() and timeline() are in scope).

ref('e_allahabad1765', 'Treaty of Allahabad, 1765', 'Wikipedia: the Diwani (revenue authority) of Bengal, Bihar and Orissa is granted to the East India Company, bringing the whole region under one administration.', 'https://en.wikipedia.org/wiki/Treaty_of_Allahabad')
ref('e_swfa', 'South-West Frontier Agency', 'Wikipedia: created in 1833 under Regulation XIII, exempting the plateau from ordinary Bengal law; comprised Manbhum, Lohardaga and Hazaribagh, with Singhbhum added after the 1837 Kolhan campaign.', 'https://en.wikipedia.org/wiki/South-West_Frontier_Agency')
ref('e_chotanagpur', 'Chota Nagpur Division', 'Wikipedia: formed in 1854 (Act XX of 1854) from the South-West Frontier Agency as a non-regulation division of Bengal, headquartered at Ranchi.', 'https://en.wikipedia.org/wiki/Chota_Nagpur_Division')
ref('e_santhalparganas', 'Santhal Pargana district', 'Wikipedia: the Sonthal Parganas Act (Act 37 of 1855), passed after the 1855 Santal rebellion, creates a separate non-regulation district administered like Chota Nagpur.', 'https://en.wikipedia.org/wiki/Santhal_Pargana_district')
ref('e_biharwb1956act', 'The Bihar and West Bengal (Transfer of Territories) Act, 1956', 'Indian Kanoon: full text — transfer of the Purulia sub-division of Manbhum (excluding Chas and Chandil thanas and Patamda police station) and the part of Kishanganj sub-division east of the boundary line to West Bengal.', 'https://indiankanoon.org/doc/1439808/')
ref('e_purnia', 'Purnia district', 'Wikipedia: in Mughal times the area lay in the sarkars of Purania and Tajpur, Bengal Subah, separated by the Mahananda river; the modern district was formed by the East India Company on 14 February 1770.', 'https://en.wikipedia.org/wiki/Purnia_district')
ref('e_partition1905', 'Partition of Bengal (1905)', 'Wikipedia: Bengal is split into an eastern province and a western province joined with Bihar and Orissa; the partition is reversed at the Delhi Durbar, 12 December 1911, when Assam, Bihar and Orissa are again separated from a reunited Bengal.', 'https://en.wikipedia.org/wiki/Partition_of_Bengal_(1905)')
ref('e_junglemahals', 'Jungle Mahals', 'Wikipedia: formed 1805 under Regulation XVIII from parts of Birbhum, Burdwan and Midnapore, including the Manbhum pargana; mostly absorbed into Manbhum district when the South-West Frontier Agency was created in 1833.', 'https://en.wikipedia.org/wiki/Jungle_Mahals')
ref('e_purulia_hist', 'Purulia district — history', 'Government of West Bengal, Purulia district page: Manbhum’s headquarters moved from Manbazar to Purulia in 1838; the district was partitioned in 1956 and Purulia was born on 1 November 1956.', 'https://purulia.gov.in/history/')
ref('e_bhasaandolon', 'Bhasa Andolon', 'Government of West Bengal, Purulia district page: the Bengali-language movement in Manbhum against Hindi imposition after 1947, led by the Lok Sevak Sangha from 14 June 1948, feeding into the States Reorganisation Commission’s recommendation for a separate Purulia district.', 'https://purulia.gov.in/bhasa-andolon/')
ref('e_dhanbad_hist', 'Dhanbad district — history', 'Government of Jharkhand, Dhanbad district page: formed 24 October 1956 from the old Dhanbad subdivision plus the Chas and Chandankiyari police stations of Manbhum’s Sadar subdivision.', 'https://dhanbad.nic.in/history/')
ref('e_balasoregaz', 'Bengal District Gazetteers: Balasore', 'L. S. S. O’Malley (1907), digitised by the University of Exeter “Famine and Dearth” project: Mughal-era parganas here were grouped under the sarkars of Cuttack, Balasore and Jaleswar.', 'https://famineanddearth.exeter.ac.uk/displayhtml.html?id=fp_00076_en_bdgazetteersbalasore')
ref('e_balasore_wiki', 'Balasore', 'Wikipedia: ceded to the British under the Treaty of Deogaon, 1803; a separate Balasore district was created in October 1828; part of the Bengal Presidency until 1912, then Bihar and Orissa province, then Odisha state from 1 April 1936.', 'https://en.wikipedia.org/wiki/Balasore')
ref('e_odishaborder2025', '“Border dispute causes tension in Odisha’s Balasore as locals accuse West Bengal of encroachment”', 'The Week, 5 March 2025: the Bhograi–Ramnagar I sector dispute, the 2020 joint committee, and 2023 pillar-laying at Jaleswar and Dantan.', 'https://www.theweek.in/news/india/2025/03/05/border-dispute-causes-tension-in-odishas-balasore-as-locals-accuse-west-bengal-of-encroachment.html')
ref('e_odishaborderdisputes', 'Odisha’s Border Disputes', 'Drishti IAS: 27 disputed plots in Balasore district and some areas of Mayurbhanj district remain contested with West Bengal.', 'https://www.drishtiias.com/daily-news-analysis/odisha-s-border-disputes')
ref('e_seraikela', 'Seraikela State', 'Wikipedia: founded 1620; came under the Chhota Nagpur Commissioner after 1803; placed under Bihar and Orissa in 1912 and under Orissa province in 1936; after a tribal revolt against merger with Orissa, merged with Bihar on 18 May 1948 on the Baudkar committee’s recommendation.', 'https://en.wikipedia.org/wiki/Seraikela_State')
ref('e_mayurbhanj', 'Mayurbhanj State', 'Wikipedia: one of the largest states of the Eastern States Agency’s Orissa States Agency; acceded to India and merged with Orissa province on 1 January 1949.', 'https://en.wikipedia.org/wiki/Mayurbhanj_State')
ref('e_esa', 'Eastern States Agency', 'Wikipedia: formed 1 April 1933 from the former Orissa Tributary States and Chota Nagpur States, until then under the suzerainty of Bihar and Orissa, plus the Central Provinces states; grouped states such as Seraikela, Kharsawan and Mayurbhanj.', 'https://en.wikipedia.org/wiki/Eastern_States_Agency')
ref('e_radcliffeboundary', 'Radcliffe Line', 'Wikipedia: the Bengal Boundary Commission’s award, completed by 12 August and published 17 August 1947, applied “contiguous majority areas” of Muslims and non-Muslims with other factors weighed in; Muslim-majority Murshidabad went to India and Hindu-majority Khulna went to Pakistan.', 'https://en.wikipedia.org/wiki/Radcliffe_Line')
ref('e_berubari', 'Berubari Union', 'GKToday: an 8.75 sq mi, 12,000-strong tract in Jalpaiguri district left ambiguous by the Radcliffe award; the 1958 Nehru–Noon Agreement proposed dividing it equally with Pakistan; the Supreme Court held on 14 March 1960 that ceding territory needs a constitutional amendment, producing the Constitution (Ninth Amendment) Act, 1960 — the transfer was never carried out and Berubari stayed with India.', 'https://www.gktoday.in/berubari-union/')
ref('e_tinbigha', 'Tin Bigha Corridor', 'Wikipedia: Bangladesh’s Dahagram–Angarpota enclave was left isolated inside Indian territory after the 1971 partition; the 1974 Land Boundary Agreement provided for India to hand over a 178-by-85-metre corridor, which opened for only 12 daylight hours until a 6 September 2011 treaty made it a 24-hour crossing from 19 October 2011.', 'https://en.wikipedia.org/wiki/Tin_Bigha_Corridor')
ref('e_indbdenclaves', 'India–Bangladesh enclaves', 'Wikipedia: the 1974 Land Boundary Agreement, the September 2011 Additional Protocol under Manmohan Singh and Sheikh Hasina, and the Constitution (100th Amendment) Act, 2015 (passed 7 May, assented 28 May, ratified during Modi’s 6 June 2015 visit to Dhaka) — India received 51 enclaves (7,110 acres) and transferred 111 (17,160 acres), effective 31 July 2015.', 'https://en.wikipedia.org/wiki/India%E2%80%93Bangladesh_enclaves')

timeline('Bihar|Jharkhand',
    ('1765', 'The Diwani granted after the Treaty of Allahabad puts Bengal, Bihar and Orissa under one East India Company administration; the Chota Nagpur plateau is still a patchwork of tributary chiefdoms on its south-western fringe.', ['e_allahabad1765']),
    ('1833', 'After the Kol uprising of 1831–32, Regulation XIII of 1833 creates the South-West Frontier Agency over Manbhum, Lohardaga and Hazaribagh; Singhbhum is added in 1837.', ['e_swfa']),
    ('1854', 'Act XX of 1854 renames the agency the Chota Nagpur Division, a non-regulation division of the Bengal Presidency headquartered at Ranchi.', ['e_chotanagpur']),
    ('1855–56', 'After the Santal rebellion, the Sonthal Parganas Act (Act 37 of 1855) carves out a separate non-regulation Santal Parganas district, administered on similar lines to Chota Nagpur but kept distinct from it.', ['e_santhalparganas']),
    ('22 Mar 1912', 'Bihar and Orissa is separated from Bengal as its own province, taking the Chota Nagpur Division and the Santhal Parganas with it; they sit alongside the Patna, Tirhut and Bhagalpur divisions that make up the rest of Bihar.', ['biharorissa']),
    ('1 Apr 1936', 'Orissa is separated in turn, leaving Bihar as a province on its own; Chota Nagpur and the Santhal Parganas remain its southern and south-eastern divisions.', ['biharorissa', 'm24']),
    ('15 Nov 2000', 'The Bihar Reorganisation Act, 2000 creates Jharkhand from the Chota Nagpur and Santhal Pargana divisions of South Bihar, fixing the Bihar–Jharkhand boundary along essentially the same division line inherited from 1854 and 1855.', ['m9', 'm29']),
)

timeline('Bihar|West Bengal',
    ('Mughal era', 'In the Kishanganj–Purnea sector the area lies in the sarkars of Purania and Tajpur of Bengal Subah, separated by the Mahananda river — the earliest traceable line close to today’s boundary here.', ['e_purnia']),
    ('1765', 'The Diwani granted after the Treaty of Allahabad puts Bengal, Bihar and Orissa under one East India Company administration.', ['e_allahabad1765']),
    ('14 Feb 1770', 'The Company forms Purnea as a British district, administered from within Bengal up to the Mahananda.', ['e_purnia']),
    ('1905', 'The Partition of Bengal joins Bihar and Orissa with the western Bengali districts in one province, reducing Bengali speakers there to a minority.', ['e_partition1905']),
    ('12 Dec 1911', 'The partition is reversed at the Delhi Durbar: the Bengali-speaking districts are reunited, and Assam, Bihar and Orissa are separated out again.', ['e_partition1905']),
    ('22 Mar 1912', 'Bihar and Orissa becomes its own province, fixing a Bihar–Bengal provincial line along the old district edges, including the Mahananda in the Purnea/Kishanganj sector and the Manbhum/Chota Nagpur edge further south.', ['biharorissa']),
    ('1 Apr 1936', 'Orissa separates in turn, leaving Bihar as a province on its own alongside Bengal.', ['biharorissa', 'm24']),
    ('1956', 'On the States Reorganisation Commission’s recommendation, the Bihar and West Bengal (Transfer of Territories) Act, 1956 moves the part of Kishanganj sub-division east of the Mahananda into Darjeeling district, and the Purulia sub-division of Manbhum (minus Chas and Chandil thanas and Patamda police station) into a new Purulia district of West Bengal — fixing the present boundary.', ['m3', 'e_biharwb1956act']),
)

timeline('Jharkhand|West Bengal',
    ('1805', 'Regulation XVIII of 1805 creates the Jungle Mahals, an area drawn from Birbhum, Burdwan and Midnapore that includes the Manbhum pargana — the earliest traceable administrative root of this frontier.', ['e_junglemahals']),
    ('1833', 'Regulation XIII of 1833 dissolves the Jungle Mahals into the new South-West Frontier Agency; most of its territory, including Manbhum, is consolidated into Manbhum district, with headquarters at Manbazar.', ['e_junglemahals', 'e_swfa']),
    ('1838', 'Manbhum’s headquarters moves to Purulia.', ['e_purulia_hist']),
    ('1854', 'Manbhum becomes part of the newly formed Chota Nagpur Division, a non-regulation division of Bengal.', ['e_chotanagpur']),
    ('22 Mar 1912', 'Bihar and Orissa is separated from Bengal as its own province, taking Chota Nagpur and Manbhum with it; the Manbhum–Bankura/Burdwan edge becomes a full provincial boundary against Bengal.', ['biharorissa']),
    ('1948–55', 'In Bihar, Hindi is imposed on Bengali-speaking Manbhum; the Lok Sevak Sangha, formed 14 June 1948, leads a language movement (the Bhasa Andolon), including a 1954 Tusu Satyagraha, pressing for transfer to West Bengal.', ['e_bhasaandolon']),
    ('Aug–1 Nov 1956', 'Parliament passes the Bihar and West Bengal (Transfer of Territories) Act and Manbhum is partitioned: its Purulia sub-division (minus Chas and Chandil thanas and Patamda police station) becomes Purulia district of West Bengal on 1 November 1956, while the Dhanbad subdivision plus the Chas and Chandankiyari police stations become Dhanbad district of Bihar on 24 October 1956.', ['m3', 'e_biharwb1956act', 'e_dhanbad_hist', 'e_purulia_hist']),
    ('15 Nov 2000', 'The Bihar Reorganisation Act, 2000 carries Dhanbad and the rest of the Chota Nagpur and Santhal Pargana divisions into the new state of Jharkhand, which inherits the 1956 line as its border with West Bengal unchanged.', ['m9']),
)

timeline('Odisha|West Bengal',
    ('Mughal era', 'The coast here is organised into the sarkars of Cuttack, Balasore and Jaleswar; Jaleswar, closest to Bengal proper, is the earliest traceable precursor of a distinct line near modern Midnapore.', ['e_balasoregaz']),
    ('17 Dec 1803', 'By the Treaty of Deogaon, Raghoji II Bhonsle of Nagpur cedes Cuttack and Balasore to the East India Company, which forms the Orissa Division of the Bengal Presidency alongside Bengal’s own Midnapore district.', ['e_balasore_wiki']),
    ('Oct 1828', 'Balasore is created as a separate district of the Bengal Presidency; its edge against Midnapore becomes the effective Bengal–Orissa line in this sector.', ['e_balasore_wiki']),
    ('22 Mar 1912', 'Bihar and Orissa is separated from Bengal as its own province, taking the Orissa Division — Cuttack, Puri and Balasore — with it; the Balasore–Midnapore edge becomes a full provincial boundary.', ['biharorissa', 'e_balasore_wiki']),
    ('1 Apr 1936', 'Orissa is constituted a province of its own under the Government of India (Constitution of Orissa) Order, 1936; the Balasore–Midnapore line becomes Orissa’s border with Bengal, and later Odisha’s with West Bengal.', ['m24', 'e_balasore_wiki']),
    ('2020', 'After recurring local friction, Odisha and West Bengal set up a joint high-level committee to demarcate the border more clearly.', ['e_odishaborder2025']),
    ('2023', 'Boundary pillars are installed on the West Bengal side at Dantan and on the Odisha side at Jaleswar, but the Bhograi (Odisha)–Ramnagar I (West Bengal) sector remains disputed.', ['e_odishaborder2025']),
    ('Feb 2025–present', 'Villagers at Sahabajipur in Balasore district dismantle newly placed West Bengal pillars they say extend into Odisha; Odisha continues to press 27 disputed plots in Balasore district and further claims in Mayurbhanj district.', ['e_odishaborder2025', 'e_odishaborderdisputes']),
)

timeline('Jharkhand|Odisha',
    ('1620–1803', 'Seraikela, one of the small Rajput states on Chota Nagpur’s southern edge, is founded in 1620; after the Second Anglo-Maratha War it becomes a princely state under British suzerainty, administered through the Chhota Nagpur Commissioner alongside neighbouring Kharsawan.', ['e_seraikela']),
    ('22 Mar 1912', 'Bihar and Orissa becomes a single province; Seraikela and Kharsawan, and the tributary states to their south that will become Mayurbhanj’s and Keonjhar’s neighbours, all fall within it.', ['biharorissa', 'e_seraikela']),
    ('1 Apr 1933', 'The Eastern States Agency is formed from the former Chota Nagpur and Orissa Tributary States, until then under the suzerainty of Bihar and Orissa; it groups Seraikela, Kharsawan, Mayurbhanj and their neighbours together.', ['e_esa']),
    ('1 Apr 1936', 'When Orissa becomes a separate province, Seraikela and Kharsawan — geographically part of the Chota Nagpur plateau — are placed under Orissa’s political authority rather than Bihar’s, setting up the later dispute.', ['e_seraikela', 'm24']),
    ('1 Jan 1948', 'Most Orissa tributary states, including Mayurbhanj’s neighbours, merge into Orissa province; in Seraikela and Kharsawan the mostly tribal population revolts against merger with Orissa.', ['e_seraikela']),
    ('18 May 1948', 'On the recommendation of the Baudkar committee set up to investigate the unrest, Seraikela and Kharsawan are merged into Bihar instead, joining Singhbhum district and the Chota Nagpur Division.', ['e_seraikela']),
    ('1 Jan 1949', 'Mayurbhanj, one of the largest states of the Eastern States Agency and a salute state of the Orissa States Agency, finally accedes and merges into Orissa province, fixing its northern edge against Bihar’s Singhbhum.', ['e_mayurbhanj']),
    ('15 Nov 2000', 'The Bihar Reorganisation Act, 2000 creates Jharkhand from the Chota Nagpur Division, including Singhbhum with Seraikela and Kharsawan; the Jharkhand–Odisha line is essentially the 1948–49 Eastern States Agency partition between Singhbhum and Mayurbhanj/Keonjhar.', ['m9']),
)

timeline('Bangladesh|West Bengal',
    ('Aug 1947', 'The Bengal Boundary Commission under Cyril Radcliffe, working from “contiguous majority areas” of Muslims and non-Muslims plus other factors, completes its award by 12 August; it is published 17 August. Anomalies follow the demographic rule imperfectly — Muslim-majority Murshidabad goes to India, Hindu-majority Khulna to Pakistan — leaving the new line vague or disputed in several places.', ['m13', 'e_radcliffeboundary']),
    ('1958', 'The Nehru–Noon Agreement proposes settling one such ambiguity, the Berubari Union in Jalpaiguri district, by dividing it equally between India and Pakistan along with an exchange of adjoining Cooch Behar enclaves.', ['e_berubari']),
    ('14 Mar 1960', 'The Supreme Court advises that ceding Indian territory needs a constitutional amendment, not just executive agreement; the Constitution (Ninth Amendment) Act, 1960 is passed to permit it, but the Berubari transfer is never carried out and the union remains with India.', ['e_berubari']),
    ('1971', 'East Pakistan becomes independent Bangladesh after the Liberation War; the former Radcliffe line here becomes the India–Bangladesh border, still leaving Bangladesh’s Dahagram–Angarpota enclave isolated inside Indian territory.', ['e_tinbigha']),
    ('16 May 1974', 'The Indira Gandhi–Sheikh Mujibur Rahman Land Boundary Agreement provides for exchanging enclaves, resolving adverse possessions and leasing India a corridor in perpetuity to connect Dahagram–Angarpota to Bangladesh; India delays ratification for decades.', ['e_indbdenclaves', 'e_tinbigha']),
    ('6 Sep 2011', 'A Protocol to the 1974 Agreement, signed by Manmohan Singh and Sheikh Hasina, settles the remaining undemarcated stretch, adverse possessions and a list of 162 enclaves to swap; the Tin Bigha corridor becomes a 24-hour crossing from 19 October 2011.', ['e_indbdenclaves', 'e_tinbigha']),
    ('31 Jul 2015', 'The Constitution (100th Amendment) Act, 2015 gives effect to the 1974 Agreement and 2011 Protocol: India transfers 111 enclaves (17,160 acres) to Bangladesh and receives 51 (7,110 acres), fixing the present West Bengal–Bangladesh boundary.', ['m28', 'e_indbdenclaves']),
)
