# South: Andhra Pradesh, Telangana, Karnataka, Tamil Nadu, Odisha, Puducherry (Yanam), Maharashtra.
# Executed inside timelines.py (ref() and timeline() are in scope).

ref('s_circars', 'Northern Circars', 'Wikipedia: Nizam Ali Khan’s grant of 12 November 1766, confirmed by the Treaty of Masulipatnam (1 March 1768); the five circars (Chicacole, Rajahmundry, Ellore, Kondapalli and Guntur) were governed as part of Madras Presidency until 1947.', 'https://en.wikipedia.org/wiki/Northern_Circars')
ref('s_ceded1800', 'Ceded Districts', 'Wikipedia: Cuddapah, Kurnool, Bellary and Anantapur, south of the Tungabhadra, ceded by Nizam Ali Khan to the East India Company in 1800 under the subsidiary-alliance arrangement, and added to Madras Presidency.', 'https://en.wikipedia.org/wiki/Ceded_Districts')
ref('s_hyderabadstate', 'Hyderabad State', 'Wikipedia: borders with Madras and Bombay presidencies; Operation Polo (13–17 September 1948); the 1956 split of the state among Andhra Pradesh, Bombay State and Mysore.', 'https://en.wikipedia.org/wiki/Hyderabad_State')
ref('s_andhrastateact', 'Andhra State Act, 1953', 'Wikipedia: assented 14 September 1953, commenced 1 October 1953; eleven Telugu districts of Madras State became Andhra State; Alur, Adoni and Rayadrug taluks of Bellary went to Andhra (into Kurnool and Anantapur districts) and the rest of Bellary to Mysore State.', 'https://en.wikipedia.org/wiki/Andhra_State_Act,_1953')
ref('s_apreorg2014', 'Andhra Pradesh Reorganisation Act, 2014', 'Wikipedia: assented 1 March 2014, in force 2 June 2014, creating Telangana; section 3 defines the two states by district; a July 2014 amendment act moved seven Khammam mandals to Andhra Pradesh for the Polavaram project.', 'https://en.wikipedia.org/wiki/Andhra_Pradesh_Reorganisation_Act,_2014')
ref('s_mysorekingdom', 'Kingdom of Mysore', 'Wikipedia: after Tipu Sultan’s fall at Seringapatam in 1799, the British restore a reduced kingdom under the Wadiyar dynasty as a subsidiary-alliance princely state; part of his former territory is annexed and divided between Madras Presidency and the Nizam.', 'https://en.wikipedia.org/wiki/Kingdom_of_Mysore')
ref('s_mysorestate', 'Mysore State', 'Wikipedia: transfer of Bellary district to Mysore in 1953; the States Reorganisation Act of 1 November 1956 adding Bombay’s and Hyderabad’s Kannada districts (including Raichur, Kalaburagi and Bidar), South Kanara and Coorg.', 'https://en.wikipedia.org/wiki/Mysore_State')
ref('s_mysorerename', 'Mysore State (Alteration of Name) Act, 1973', 'Indian Kanoon: renames Mysore State as Karnataka with effect from 1 November 1973.', 'https://indiankanoon.org/doc/45260278/')
ref('s_sribagh', 'Sribagh Pact', 'Wikipedia: signed 16 November 1937 by Coastal Andhra and Rayalaseema leaders, setting terms — universities, irrigation priority, decentralised institutions — for jointly seeking a separate Telugu-speaking province.', 'https://en.wikipedia.org/wiki/Sribagh_Pact')
ref('s_historyap', 'History of Andhra Pradesh', 'Wikipedia: Potti Sriramulu’s fast for a separate Andhra state and his death on 15 December 1952; Nehru’s announcement of 19 December 1952; Andhra State formed 1 October 1953.', 'https://en.wikipedia.org/wiki/History_of_Andhra_Pradesh')
ref('s_capitalsouthfirst', '“From Kurnool to Amaravati: Andhra Pradesh’s long struggle to find a suitable capital”', 'The South First: C. Rajagopalachari’s refusal to let Madras city become Andhra’s capital, and the Sribagh Pact compromise that made Kurnool the capital.', 'https://thesouthfirst.com/andhrapradesh/from-kurnool-to-amaravati-andhra-pradeshs-long-struggle-to-find-a-suitable-capital/')
ref('s_apmadras1959', 'Andhra Pradesh and Madras Alteration of Boundaries Act, 1959', 'Wikipedia: enacted 24 December 1959, in force 1 April 1960; Tiruttani taluk and Pallipattu sub-taluk of Chittoor district (319 villages) moved from Andhra Pradesh to Madras State in exchange for 148 villages of Chingleput district and 3 of Salem district.', 'https://en.wikipedia.org/wiki/Andhra_Pradesh_and_Madras_Alteration_of_Boundaries_Act,_1959')
ref('s_madrasstate', 'Madras State', 'Wikipedia: renamed Tamil Nadu on 14 January 1969.', 'https://en.wikipedia.org/wiki/Madras_State')
ref('s_orissaprovince', 'Orissa Province', 'Wikipedia: created 1 April 1936 by partitioning Bihar and Orissa Province; parts of Madras Presidency’s Ganjam and Vizagapatam districts, and of their Hill Tracts Agencies, transferred in along with the Khariar region of the Central Provinces.', 'https://en.wikipedia.org/wiki/Orissa_Province')
ref('s_kotia', 'Kotia (disputed territory)', 'Wikipedia: pre-1936 undivided Vizagapatam district and its Salur Agency; the 1920 transfer of 123 villages from Salur Agency to Pottangi taluka and the 1927–28 retransfer of 115 villages (only 7 of the later-disputed 21) back to Salur; Odisha’s continuous administration since 1936/1952 and the Supreme Court’s 1968 stay and 2006 observations.', 'https://en.wikipedia.org/wiki/Kotia_(disputed_territory)')
ref('s_yanaon', 'Yanaon', 'Wikipedia: the 1723 French purchase of land near Injaram-Yanaon, the 1731 loge at Venjaram pargana in Rajamahendri Circar, Nizam Muzaffar Jung’s December 1750 grant of sovereignty confirmed by the Mughal emperor’s firman of 14 May 1753, the 13 June 1954 seizure led by Dadala Raphael Ramanayya, France’s 1 November 1954 de facto transfer, and the 16 August 1962 de jure cession.', 'https://en.wikipedia.org/wiki/Yanaon')
ref('s_dejure1962', 'Treaty establishing De Jure Cession of French Establishments in India', 'Wikipedia: signed 28 May 1956 by Stanislas Ostroróg and Jawaharlal Nehru, ceding Pondicherry, Karaikal, Mahé and Yanam; ratified 16 August 1962.', 'https://en.wikipedia.org/wiki/Treaty_establishing_De_Jure_Cession_of_French_Establishments_in_India')
ref('s_marathwada', 'Marathwada', 'Wikipedia: formed under the Nizam’s rule as part of Hyderabad State; 17 September, the day of its 1948 integration into India, is commemorated as Marathwada Liberation Day.', 'https://en.wikipedia.org/wiki/Marathwada')
ref('s_bombaystate', 'Bombay State', 'Wikipedia: the States Reorganisation Act of 1 November 1956 enlarged Bombay State with Hyderabad State’s Marathi-speaking Marathwada region; the Bombay Reorganisation Act split it into Maharashtra and Gujarat on 1 May 1960 after the Samyukta Maharashtra Movement, in which 107 protesters were killed by police.', 'https://en.wikipedia.org/wiki/Bombay_State')
ref('s_kalyanakarnataka', 'Kalyana-Karnataka', 'Wikipedia: the Bidar, Yadgir, Raichur, Koppal and Kalaburagi (Gulbarga) districts of the former Nizam-ruled Hyderabad State were incorporated into Mysore State under the States Reorganisation Act of 1956; the region, long called Hyderabad-Karnataka, was officially renamed Kalyana-Karnataka in 2019.', 'https://en.wikipedia.org/wiki/Kalyana-Karnataka')

timeline('Andhra Pradesh|Telangana',
    ('12 Nov 1766', 'Nizam Ali Khan grants the East India Company the five Northern Circars (Chicacole, Rajahmundry, Ellore, Kondapalli and Guntur), confirmed by the Treaty of Masulipatnam in 1768; the inland edge of this coastal strip against the Nizam’s remaining Telangana districts becomes the earliest fixed line between what are now coastal Andhra Pradesh and Telangana.', ['s_circars']),
    ('1800', 'The Nizam cedes Cuddapah, Kurnool, Bellary and Anantapur — the Ceded Districts, south of the Tungabhadra — to the Company for Madras Presidency, extending the same Nizam/British line along the Rayalaseema side.', ['s_ceded1800']),
    ('19th c.–1948', 'The Nizam’s Hyderabad State and British Madras Presidency administer their sides as separate jurisdictions; Hyderabad, landlocked after 1766, keeps Telangana districts such as Warangal, Nalgonda and Khammam against Madras’s coastal and ceded districts.', ['s_circars', 's_hyderabadstate']),
    ('13–17 Sep 1948', 'The Indian Army’s Operation Polo ends Hyderabad State’s independent rule; the state, with the old Nizam/Madras line intact, is integrated into the Indian Union.', ['s_hyderabadstate']),
    ('1 Oct 1953', 'The Andhra State Act creates Andhra State from Madras State’s eleven Telugu-speaking districts (coastal Andhra and Rayalaseema); its inland edge against Hyderabad State remains the old Nizam/Madras line.', ['s_andhrastateact']),
    ('1 Nov 1956', 'The States Reorganisation Act merges Andhra State with the Telugu-speaking Telangana districts of Hyderabad State (the rest of Hyderabad going to Bombay State and Mysore) to form Andhra Pradesh; the old Nizam/Madras line survives internally as the boundary between the former Andhra State and former Hyderabad State districts.', ['m2', 's_hyderabadstate']),
    ('2 Jun 2014', 'The Andhra Pradesh Reorganisation Act, 2014 splits the state again into Telangana and residuary Andhra Pradesh; section 3 defines Telangana by listing the former Hyderabad State districts, so the line reverts almost exactly to the pre-1956 Nizam/Madras edge.', ['m10', 's_apreorg2014']),
    ('Jul 2014', 'An amendment act moves seven Khammam mandals (Kukunoor, Velairpadu, Burgampahad, Chintoor, Kunavaram, Vararamachandrapuram and Bhadrachalam) into Andhra Pradesh’s East and West Godavari districts for Polavaram dam rehabilitation, excluding Bhadrachalam town and twelve named revenue villages so the only road access to the town stays in Telangana.', ['m11', 's_apreorg2014']),
)

timeline('Andhra Pradesh|Karnataka',
    ('1799', 'After the fourth Anglo-Mysore War and the fall of Seringapatam, the British restore a much-reduced Kingdom of Mysore under the Wadiyar dynasty as a subsidiary-alliance princely state; part of Tipu Sultan’s former territory is annexed and divided between Madras Presidency and the Nizam.', ['s_mysorekingdom']),
    ('1800', 'The Nizam cedes Cuddapah, Kurnool, Bellary and Anantapur — the Ceded Districts, south of the Tungabhadra — to Madras Presidency; their western edge against the restored Mysore kingdom becomes the origin of today’s Andhra Pradesh–Karnataka line.', ['s_ceded1800']),
    ('19th c.–1948', 'Bellary, Anantapur and Kurnool remain Madras Presidency districts against the Mysore princely state to their west, while further north Raichur district of the Nizam’s Hyderabad State borders Kurnool — a Madras/Hyderabad stretch that later becomes part of the same interstate line.', ['s_ceded1800', 's_hyderabadstate']),
    ('1 Oct 1953', 'The Andhra State Act partitions Bellary district on the recommendation of the L. S. Misra Commission, set up to weigh its mixed Telugu- and Kannada-speaking population: Alur, Adoni and Rayadrug taluks join Andhra State, added to Kurnool and Anantapur districts, while the rest of Bellary goes to Mysore State.', ['s_andhrastateact']),
    ('1 Nov 1956', 'The States Reorganisation Act enlarges Mysore State with the Kannada-speaking Raichur, Gulbarga (Kalaburagi) and Bidar districts of Hyderabad State, plus Bombay State’s Kannada districts, South Kanara and Coorg, while merging Andhra State with Telangana into Andhra Pradesh; the Andhra Pradesh–Karnataka line now combines the 1953 Bellary partition with the old Madras/Hyderabad Kurnool–Raichur edge.', ['m2', 's_mysorestate']),
    ('1 Nov 1973', 'Mysore State is renamed Karnataka; the boundary itself is unchanged.', ['s_mysorerename']),
)

timeline('Andhra Pradesh|Tamil Nadu',
    ('16 Nov 1937', 'Coastal Andhra and Rayalaseema leaders sign the Sribagh Pact, agreeing terms for jointly pursuing a separate Telugu-speaking province out of Madras Presidency; Madras city and the Tamil districts are not part of the proposal.', ['s_sribagh']),
    ('15 Dec 1952', 'Potti Sriramulu dies after a fast for a separate Andhra state; four days later, on 19 December, Nehru announces in the Lok Sabha that Andhra State will be formed from the Telugu districts of Madras State.', ['s_historyap']),
    ('1952–53', 'Madras’s chief minister C. Rajagopalachari refuses to let the new state take Madras city as its capital; the Sribagh Pact’s compromise makes Kurnool, not Madras, the Andhra capital.', ['s_capitalsouthfirst']),
    ('1 Oct 1953', 'The Andhra State Act creates Andhra State from Madras State’s eleven Telugu-speaking districts (plus three Bellary taluks); Madras city and its Tamil-majority hinterland stay in Madras State, so the new interstate line runs just north of the city rather than through it.', ['s_andhrastateact']),
    ('1 Nov 1956', 'The States Reorganisation Act merges Andhra State with Telangana to form Andhra Pradesh; the 1953 line with Madras State is unaffected.', ['m2', 's_andhrastateact']),
    ('24 Dec 1959 / 1 Apr 1960', 'The Andhra Pradesh and Madras (Alteration of Boundaries) Act exchanges territory along the line: Tiruttani taluk and Pallipattu sub-taluk of Chittoor district (319 villages) move from Andhra Pradesh to Madras State, in return for 148 villages of Chingleput district and 3 of Salem district.', ['s_apmadras1959']),
    ('14 Jan 1969', 'Madras State is renamed Tamil Nadu; the boundary set in 1953 and adjusted in 1960 is unchanged.', ['s_madrasstate']),
)

timeline('Andhra Pradesh|Odisha',
    ('Pre-1936', 'Ganjam and Vizagapatam, including the Vizagapatam Hill Tracts Agency and its Jeypore Zamindari and Salur Agency tracts, are administered as a single stretch of Madras Presidency.', ['s_kotia']),
    ('1920', 'The Salur Agency is abolished and 123 of its villages are transferred to Pottangi taluka, within the same Madras Presidency district — an internal reshuffle that later becomes the root of a cross-border dispute.', ['s_kotia']),
    ('1927–28', 'The Madras government retransfers 115 villages from Pottangi back to Salur, but only 7 of the 21 villages later disputed as “Kotia” are among them, leaving the other 14 in Pottangi.', ['s_kotia']),
    ('1 Apr 1936', 'The Government of India (Constitution of Orissa) Order, acting on the O’Donnell Boundary Committee’s recommendations, carves Orissa Province out of Madras Presidency’s Ganjam and Vizagapatam districts and their Hill Tracts Agencies; Pottangi taluka (with 14 of the future Kotia villages) goes to Orissa’s Koraput district while Salur (with the other 7) stays in Madras.', ['m24', 's_orissaprovince']),
    ('Since 1936/1952', 'Odisha administers all 21 Kotia villages continuously from 1936, holding regular elections there since 1952; Andhra Pradesh nonetheless claims them as part of Salur (now in Parvathipuram Manyam district), citing the 1920s notifications, so residents end up holding both states’ identity documents.', ['s_kotia']),
    ('1968 / 2006', 'The Supreme Court stays further development in the disputed villages in 1968 and, in 2006, observes that Parliament — not the courts — should resolve this pre-Constitution boundary dispute; it remains unresolved.', ['s_kotia']),
)

timeline('Andhra Pradesh|Puducherry',
    ('24 Jan 1723', 'A French agent buys land near Injaram, by the Godavari, to found a trading post at Yanaon.', ['s_yanaon']),
    ('30 Jul 1731', 'The French re-establish a loge at Yanaon within the paragana of Venjaram, part of the Rajamahendri (Rajahmundry) Circar — the village-level footing on which the enclave’s limits are later fixed, rather than a later British district line.', ['s_yanaon']),
    ('Dec 1750 / 14 May 1753', 'Nizam Muzaffar Jung grants the French sovereignty over Yanaon (with Karaikal and Pondicherry); the Mughal emperor’s firman of 14 May 1753 confirms the grant, fixing Yanaon as a small French enclave inside what becomes the Northern Circars.', ['s_yanaon', 's_circars']),
    ('1766–1953', 'The surrounding territory passes from the Nizam’s grant of the Northern Circars to British Madras Presidency and then to Madras State’s (from 1953, Andhra State’s) Godavari districts, while Yanaon stays French, its boundary still the old factory/pargana limits.', ['s_circars', 's_andhrastateact']),
    ('13 Jun 1954', 'Indian civilians led by Dadala Raphael Ramanayya seize Yanaon in a coup d’état against French rule.', ['s_yanaon']),
    ('1 Nov 1954', 'After a referendum in which 170 of 178 members of the Representative Council vote to join India, France accepts the fait accompli and de facto transfers Pondicherry, Karaikal, Mahé and Yanam to the Indian Union.', ['s_dejure1962', 's_yanaon']),
    ('28 May 1956 / 16 Aug 1962', 'France and India sign the Treaty of Cession on 28 May 1956; France ratifies it and the instruments are exchanged on 16 August 1962, completing the de jure transfer of Yanam, now part of the Union Territory of Puducherry, surrounded entirely by Andhra Pradesh’s East Godavari district.', ['m20', 's_dejure1962']),
)

timeline('Maharashtra|Telangana',
    ('1724', 'Nizam-ul-Mulk founds Hyderabad State in the Deccan, covering what are now Telangana, the Marathwada region of Maharashtra and the Kalyana-Karnataka region of Karnataka; its western edge borders the Bombay Presidency’s Marathi-speaking districts, the origin of today’s line.', ['s_hyderabadstate']),
    ('19th–20th c.', 'Hyderabad State and British Bombay Presidency administer their sides as separate jurisdictions; the Marathi-speaking Marathwada districts (Aurangabad, Bhir, Nanded, Parbhani, Osmanabad) stay inside Hyderabad State throughout British rule, kept apart from the Telugu-speaking Telangana districts only by internal Hyderabad administrative lines.', ['s_hyderabadstate', 's_marathwada']),
    ('17 Sep 1948', 'The Indian Army’s Operation Polo ends Hyderabad State’s independent rule; Marathwada’s integration into India is commemorated as Marathwada Liberation Day, and the state, with its old western boundary against Bombay Presidency intact, joins the Union.', ['s_hyderabadstate', 's_marathwada']),
    ('1 Nov 1956', 'The States Reorganisation Act enlarges Bombay State with Hyderabad State’s Marathi-speaking Marathwada region, while Hyderabad’s Telugu-speaking Telangana districts go to Andhra Pradesh; the old internal Hyderabad line between its Marathi and Telugu districts becomes the new Bombay State–Andhra Pradesh boundary.', ['m2', 's_bombaystate']),
    ('1 May 1960', 'The Bombay Reorganisation Act splits Bombay State into Maharashtra and Gujarat after the Samyukta Maharashtra Movement; Marathwada goes to Maharashtra, so the 1956 line becomes the Maharashtra–Andhra Pradesh boundary.', ['m4', 's_bombaystate']),
    ('2 Jun 2014', 'The Andhra Pradesh Reorganisation Act creates Telangana from the former Hyderabad State’s Telugu districts; the Maharashtra boundary, unchanged since 1956, becomes the Maharashtra–Telangana border.', ['m10']),
)

timeline('Karnataka|Telangana',
    ('1724', 'Nizam-ul-Mulk founds Hyderabad State, ruling Kannada-speaking districts such as Bidar, Gulbarga (Kalaburagi) and Raichur alongside Telugu-speaking districts such as Nizamabad, Medak, Mahbubnagar and Nalgonda within one princely state; the line between them is only an internal district boundary.', ['s_hyderabadstate']),
    ('British period', 'Hyderabad State keeps its Kannada-speaking northwest — Bidar, Gulbarga and Raichur, later called Hyderabad-Karnataka — contiguous with its Telugu-speaking districts to the east; no interstate boundary exists because both sides answer to the same Nizam.', ['s_kalyanakarnataka']),
    ('17 Sep 1948', 'The Indian Army’s Operation Polo ends Hyderabad State’s independent rule; its internal Kannada/Telugu district line is unaffected.', ['s_hyderabadstate']),
    ('1 Nov 1956', 'The States Reorganisation Act splits Hyderabad State on linguistic lines: Bidar, Gulbarga and Raichur join Mysore State while Nizamabad, Medak, Mahbubnagar, Nalgonda and the other Telugu districts join Andhra Pradesh (merged with Andhra State); the former internal Hyderabad district line becomes an interstate boundary for the first time.', ['m2', 's_kalyanakarnataka']),
    ('1 Nov 1973', 'Mysore State is renamed Karnataka; the boundary is unchanged.', ['s_mysorerename']),
    ('2 Jun 2014', 'The Andhra Pradesh Reorganisation Act carves Telangana out of Andhra Pradesh from the former Hyderabad State’s Telugu districts; the 1956 line becomes the Karnataka–Telangana border.', ['m10']),
    ('2019', 'The Bidar–Kalaburagi–Yadgir–Raichur–Koppal region, long known as Hyderabad-Karnataka, is officially renamed Kalyana-Karnataka; the boundary itself does not change.', ['s_kalyanakarnataka']),
)
